name: MissileWars
version: ${project.version}
depend: [WorldEdit,WorldGuard]
softdepend: [Vault]
main: me.jackz.missilewars.MissileWars
load: POSTWORLD
api-version: 1.13
commands:
  spectate:
    description: Join the spectators
    usage: /spectate
  game:
    aliases: [gameinfo]
    description: view game statistics and information
    usage: /game
  stats:
    aliases: [wins,loses,stat]
    description: View game stats for a player
    usage: /stats [player]
  missilewarsadmin:
    aliases: [mwa]
    description: admin
    usage: /mwa help

permissions:
  missilewars.stats.*:
    description: Allows to view all types of statistics
    default: true
  missilewars.spectate:
    description: Allow switching between spectating
    default: true
    children:
      missilewars.spectate.others: false
  missilewars.admin:
    description: Allows access to the /missilewarsadmin command
    default: op
    children:
      missilewars.admin.choose: true
      missilewars.admin.give: true
      missilewars.admin.config: false
      missilewars.admin.config.save: false
      missilewars.admin.game.stop: false
      missilewars.admin.game.start: true

